name: Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout github repo
      uses: actions/checkout@v3
      with:
        lfs: true
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest mypy
        pip install -r requirements.txt
    - name: Download models
      run: |
        bash download_models.sh
    - name: Lint
      run: |
        flake8 nyan/ --count --ignore=C901,E741,W503,PIE786,E203 --show-source --statistics
        flake8 nyan/ --count --exit-zero --max-complexity=10 --statistics
        mypy --strict nyan/
    - name: PyTest
      run: |
        pytest -s
